name: Keep Supabase Alive
on:
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Send keepalive request to Supabase REST endpoint
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          # Fail fast if secrets are missing
          if [ -z "${SUPABASE_URL}" ] || [ -z "${SUPABASE_KEY}" ]; then
            echo "Missing SUPABASE_URL or SUPABASE_KEY"
            exit 1
          fi

          # Use -G and --data-urlencode so the shell doesn't split on & or expand *
          # Remove a trailing slash from SUPABASE_URL if present with ${VAR%/}
          curl -sS -G "${SUPABASE_URL%/}/rest/v1/keepalive" \
            --data-urlencode "select=*" \
            --data-urlencode "limit=1" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}" \
            -o /dev/null -w "HTTP status: %{http_code}\n"
