name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC; adjust as needed
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Insert keepalive record to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          TS=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
          curl -sS \
            -X POST \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"timestamp\":\"$TS\"}" \
            "$SUPABASE_URL/rest/v1/keepalive"
